/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package BM;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import matrices.MatrizMinas;
import matrices.MatrizVisibles;

/**
 *
 * @author Fhany
 */
public class Principal extends javax.swing.JFrame {

    JButton Botones[][] = new JButton[10][10];
    MatrizMinas Minas = new MatrizMinas();
    MatrizVisibles Visibles = new MatrizVisibles();

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Negro = Minas || Blanco = Sin minas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ponerBotones();
        nuevaPartida();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nuevaPartida();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nuevaPartida() {
        Minas.ponerMinas();
        Minas.calcularContornos();
        Visibles.visibilizar(false);
        Visualizar();
    }

    public void pulsarBoton(Object obj) {
        for (int m = 0; m < 10; m++) {
            for (int n = 0; n < 10; n++) {
                if (obj == Botones[m][n]) {
                    pulsarCasilla(m, n);
                }
            }
        }
    }

    public void ponerBotones() {
        for (int m = 0; m < 10; m++) {
            for (int n = 0; n < 10; n++) {
                Botones[m][n] = new JButton();
                jPanel1.add(Botones[m][n]);
                Botones[m][n].setBounds(m * 50, n * 50, 50, 50);
                
                //creo una lista que capture los eventos
                Botones[m][n].addActionListener(
                        new ActionListener() {
                            public void actionPerformed(ActionEvent e) {
                                pulsarBoton(e.getSource());
                            }
                        });
            }
        }
    }

    public void pulsarCasillaRec(int m, int n) {
        if (m>=0&&m<10&&n>=0&&n<10&&Visibles.isValor(m, n) == false) {
            Visibles.setVisible(m, n, true);
            if (Minas.getMina(m, n) == 9) {
                Visibles.visibilizar(true);
            }
            if(Minas.getMina(m, n)==0){
                pulsarCasillaRec(m, n-1);
                pulsarCasillaRec(m, n+1);
                pulsarCasillaRec(m-1, n);
                pulsarCasillaRec(m+1, n);
            }
        }        
    }

    public void pulsarCasilla(int m, int n) {
        pulsarCasillaRec(m, n);
        Visualizar();
    }  

    public void Visualizar() {
        for (int m = 0; m < 10; m++) {
            for (int n = 0; n < 10; n++) {
                if (Visibles.isValor(m, n)) {
                    if (Minas.getMina(m, n) == 9) {
                        Botones[m][n].setLabel("");
                        Botones[m][n].setBackground(Color.BLACK);
                    } else if (Minas.getMina(m, n) == 0) {
                        Botones[m][n].setLabel("");
                        Botones[m][n].setBackground(Color.WHITE);
                    } else {
                        Botones[m][n].setLabel("" + Minas.getMina(m, n));
                        Botones[m][n].setBackground(Color.GRAY);
                    }
                } else {
                    Botones[m][n].setLabel("");
                    Botones[m][n].setBackground(Color.GRAY);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
